packages:
  - apps/blip-server-cloudflare
  - apps/blip-server
  - packages/blip-server-app
  - packages/blip-server-domain
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  workerd: true
patchedDependencies:
  '@distilled.cloud/cloudflare-rolldown-plugin@0.13.8': patches/@distilled.cloud__cloudflare-rolldown-plugin@0.13.8.patch
